name: Release

on:
  pull_request:
  push:
    branches: [build]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.38
        with:
            recipe-path: ./recipe/recipe.yaml
            build-args: -m .ci_support/linux_64_mpiopenmpi.yaml
      - run: ll -lh .
