name: Release

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
    branches:
      - build

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - CONFIG: linux_64_hdf51.14.6mpiopenmpi
          - CONFIG: linux_64_hdf52mpiopenmpi
          - CONFIG: linux_64_hdf52mpimpich
          - CONFIG: linux_64_hdf51.14.6mpimpich
    steps:
      - uses: actions/checkout@v6
      - name: Setup rattler-build
        uses: prefix-dev/rattler-build-action@v0.2.38
        with:
          setup-only: true
      - name: Build and upload
        run: |
          rattler-build build           \
            --output-dir dist           \
            --recipe recipe/recipe.yaml \
            -m .ci_support/${{ matrix.config }}.yaml
      - name: List the dists
        run: |
          ls -lh dist/*
      - name: Release & Upload
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "dist/linux-64/*"
