name: Release

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - CONFIG: linux_64_mpimpich
          - CONFIG: linux_64_mpiopenmpi
    steps:
      - uses: actions/checkout@v6
      - run: |
          sed -i "s/-GNinja/-GNinja -DBUILD_SHARED_LIBS=OFF/g" recipe/build.sh;
          cat recipe/build.sh;
      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.38
        with:
            recipe-path: ./recipe/recipe.yaml
            artifact-name: package-${{ matrix.config }}
            build-args: -m .ci_support/${{ matrix.config }}.yaml
      - name: Show files
        run: find . -name '*.conda'

  release:
    needs:
      - build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "package-*"